### Liste tous les joueurs
# @name ListeTousLesJoueurs
//@no-log
GET http://localhost:8080/personnes

### Liste tous les categories
# @name ListeTousLesCategories
//@no-log
GET http://localhost:8080/categories
